// Generated by: npm run setupOTA
// Public base URL for OTA (version.txt and bundle.zip). No secrets.
// Each ota:build:upload overwrites the same files at this URL.
//
// otaMode:
//   'twoUrl' — version.txt + bundle.zip at baseUrl (default; use with ota:build:upload)
//   'json'   — single JSON with { version, bundleUrl, ... } at jsonConfigUrl (tests checkAndDownloadFromConfig)

module.exports = {
  baseUrl: 'https://tc-app-distribution.s3.ap-south-1.amazonaws.com/ota',
  otaMode: 'twoUrl',
  /** Required when otaMode === 'json'. Example: `${baseUrl}/ota.json` */
  jsonConfigUrl: '',
}
