// Generated by: npm run setupOTA
// Public base URL for OTA (version.txt and bundle.zip). No secrets.
// Each ota:build:upload overwrites the same files at this URL.

module.exports = {
  baseUrl: 'https://tc-app-distribution.s3.ap-south-1.amazonaws.com/ota',
}
