#!/usr/bin/env bash
#
# Build OTA bundle and zip for react-native-nitro-update.
# Generated by: npx setup-ota
#
# Usage:
#   npm run ota:zip              # version from package.json
#   npm run ota:zip -- 1.0.2     # custom version
#   OTA_VERSION=1.0.2 npm run ota:zip
#
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
APP_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
OUT_DIR="$APP_DIR/ota-release"
ZIP_NAME="bundle.zip"
BUNDLE_FILES=""

get_version() {
  if [[ -n "${1:-}" ]]; then
    echo "$1"
  elif [[ -n "${OTA_VERSION:-}" ]]; then
    echo "$OTA_VERSION"
  else
    node -p "require('$APP_DIR/package.json').version"
  fi
}

VERSION="$(get_version "${1:-}")"

echo "Building OTA release (version: $VERSION)"
mkdir -p "$OUT_DIR"
cd "$APP_DIR"

echo "$VERSION" > "$OUT_DIR/version.txt"

echo "Bundling ios (production)..."
npx react-native bundle \
  --platform ios \
  --dev false \
  --entry-file index.js \
  --bundle-output "$OUT_DIR/index.ios.jsbundle" \
  --assets-dest "$OUT_DIR"

BUNDLE_FILES="$BUNDLE_FILES index.ios.jsbundle"

echo "Creating zip..."
cd "$OUT_DIR"
rm -f "$ZIP_NAME"
zip -q "$ZIP_NAME" $BUNDLE_FILES version.txt

echo ""
echo "Done. OTA artifacts:"
echo "  $OUT_DIR/version.txt"
echo "  $OUT_DIR/$ZIP_NAME"
ls -la "$OUT_DIR/$ZIP_NAME"
